### ISSUE TITLE
Allow events to run even when focus is lost

### ISSUE THREAD

**Issue by stevenmathews** [cyclejs/time#37]
eg. `sources.Time.periodic(1000)` pauses when I switch tabs and resumes when I come back due to `requestAnimationFrame`.

**Comment by staltz** [comment]
Hmm, I understand this, but may I ask what is the root problem? What feature are you trying to achieve by wanting the periodic to keep emitting when the tab has changed?

**Comment by stevenmathews** [comment]
Generating invoices from a [pomodoro timer](https://en.wikipedia.org/wiki/Pomodoro_Technique). Need the timer to continue while I work.

Nick asked me to open this issue but also recommended I use `Time.animationFrames()` which offers the functionality I need.

**Comment by Frikki** [comment]
Doesn’t the events pick up and synchronize when you return to the tab?

**Comment by stevenmathews** [comment]
@Frikki It pauses the time then resumes where it left off on refocus.

**Comment by staltz** [comment]
What if you don't use periodic() to track time, but just use periodic() to *sample* time? For instance with `Date.now()`. If you want a stopwatch, you can subtract from an initial timestamp.

**Comment by stevenmathews** [comment]
What is the advantage of this approach over using`Time.animationFrames()`? (wanting to learn not saying it's better).

**Comment by Widdershin** [comment]
They're comparable, but either way all it's not going to run in the background, since both of them are powered by `requestAnimationFrame` under the hood, and animations don't need to run in the background.

One option to consider, is that I just checked in Chrome and it seems like `setImmediate` still runs in the background, albeit slower, and I wouldn't be surprised if the polyfill hack using `postMessage` works as well.

I might consider powering `periodic()` and others from a `setImmediate` schedule to enable this. That additional flexibility in the design would also aid with implementing #29.

`animationFrames` and `throttleAnimation` would still be `requestAnimationFrame` powered and could be used to throttle the UI as needed, so that would be okay. We could just document how `requestAnimationFrame` works here.

**Comment by Widdershin** [comment]
Oh, and a use case as to why this is important: say you want to play a sound on a timer, it would not be great if it just didn't work at all because it was in a background tab. Much better to have it play 500ms later than not at all.

**Comment by Widdershin** [comment]
I started having a look and as I hoped the `setImmediate` polyfill runs in the background in Chrome and Firefox, so I can go ahead with this.
